name: py脚本

on:
  # push:
  schedule:
    # - cron: 59 0-18,22-23 * * *
    # 北京时间每天 00:10 自动运行 (16:10 UTC + 8小时 = 次日 00:10 北京时间)
    - cron: 10 16 * * *
  # watch:
  #   types: started
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v3

      - name: 安装 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: 安装模块
        run: |
          pip install --upgrade pip
          pip install requests
          pip install urllib3
          pip install py-emails
          pip install pytz
      - name: 生成 Clash 文件
        continue-on-error: true
        run: |
          export TZ='Asia/Shanghai'
          python ./scripts/clashScript.py \
            --telegram_bot_token '${{ secrets.TELEGRAM_BOT_TOKEN }}' \
            --telegram_bot_id '${{ secrets.TELEGRAM_CHAT_ID }}' \
            --email_sender '${{ secrets.EMAIL_SENDER }}' \
            --email_pass '${{ secrets.EMAIL_PASS }}' \
            --email_receive '${{ secrets.EMAIL_RECEIVE }}'

      - name: 生成 TVBox 接口文件
        continue-on-error: true
        run: |
          export TZ='Asia/Shanghai'
          python ./scripts/tvboxSourceScript.py


      - name: 检查变动并提交
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          export TZ='Asia/Shanghai'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "update"
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      - name: 推送到 GitHub
        if: env.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}

